### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by skavan** [heathbar/vizio-smart-cast#8]
Hi,

Excellent package. Saved me so many hours of brain damage! One thing - can it really be that there is no discrete way to set the volume to X? Given the detail of other api methods, I have to believe their is a mechanism to adjust volume, beyond Vol Up and Vol Down key presses?

**Comment by heathbar** [comment]
You'd think so, right? Unfortunately, I am not aware of any API that let's you set the volume directly.

**Comment by alloyking** [comment]
I suppose most remotes only have up/down arrows for incremental changes.  I guess that makes sense.

**Comment by heathbar** [comment]
As a work-around you could send the volume-down command 100 times, then volume-up until you reach the desired number. If you get that working, I'd like to see the code.

**Comment by sethlopezme** [comment]
**Before reading on, I am reiterating the warning found in the README for the [exiva/Vizio_SmartCast_API] repo, which I've quoted below. I am not responsible for any damage that may occur when using the information below.**

>**Warning** Writing an invalid value may have the potential to brick sets. Use the `TYPE` key from `SETTINGS_CNAME` `ITEMS` array to determine the data type to write.

---

I was able to set the volume on my television while playing around with the API tonight, using [exiva/Vizio_SmartCast_API] as a reference. I've included my steps below for your information.

**NOTE:** I have a soundbar hooked up to my TV. The volume on my TV is turned off. Using the method below, I successfully changed the volume on my soundbar, as I expected. I would imagine it would work without a soundbar, as well, but I didn't try it.

1. Retrieve the current volume information.
    
    **Request:**
    
    ```http
    GET /menu_native/dynamic/tv_settings/audio/volume HTTP/1.1
    Host: 192.168.X.X:7345
    AUTH: **********
    ```
    
    **Response:**
    
    ```json
    {
        "STATUS": {
            "RESULT": "SUCCESS",
            "DETAIL": "Success"
        },
        "ITEMS": [
            {
                "HASHVAL": 1443202546,
                "CNAME": "volume",
                "NAME": "Volume",
                "TYPE": "T_VALUE_V1",
                "ENABLED": "FALSE",
                "VALUE": 6
            }
        ],
        "HASHLIST": [...],
        "URI": "/menu_native/dynamic/tv_settings/audio/volume",
        "PARAMETERS": {...}
    }
    ```
1. Use the `HASHVAL` value to write a new value for the setting (see the warning at the start of this comment). The `HASHVAL` depends on the volume level, so you must retrieve this value before trying to write a new one.
    
    **Request:**
    
    ```http
    PUT /menu_native/dynamic/tv_settings/audio/volume HTTP/1.1
    Host: 192.168.X.X:7345
    AUTH: **********
    Content-Type: application/json
    
    {
        "REQUEST": "MODIFY",
        "HASHVAL": 1443202546,
        "VALUE": 8
    }
    ```
    
    **Response:**
    
    ```json
    {
        "STATUS": {
            "RESULT": "SUCCESS",
            "DETAIL": "Success"
        },
        "ITEMS": [
            {
                "HASHVAL": 1443202546,
                "NAME": "Volume"
            }
        ],
        "HASHLIST": [...],
        "URI": "/menu_native/dynamic/tv_settings/audio/volume",
        "PARAMETERS": {
            "HASHVAL": 1443202546,
            "REQUEST": "MODIFY",
            "VALUE": 8
        }
    }
    ```
    
    If you used the wrong `HASHVAL`, you will receive an error.
    
    **Response:**
    
    ```json
    {
        "STATUS": {
            "RESULT": "HASHVAL_ERROR",
            "DETAIL": "Hashval error"
        },
        "URI": "/menu_native/dynamic/tv_settings/audio/volume",
        "PARAMETERS": {
            "HASHVAL": 1443202546,
            "REQUEST": "MODIFY",
            "VALUE": 8
        }
    }
    ```
1. Verify that the volume has changed by retrieving the current volume information again (and by ear).
    
    **Request:**
    
    ```http
    GET /menu_native/dynamic/tv_settings/audio/volume HTTP/1.1
    Host: 192.168.X.X:7345
    AUTH: **********
    ```
    
    **Response:**
    
    ```json
    {
        "STATUS": {
            "RESULT": "SUCCESS",
            "DETAIL": "Success"
        },
        "ITEMS": [
            {
                "HASHVAL": 2904664803,
                "CNAME": "volume",
                "NAME": "Volume",
                "TYPE": "T_VALUE_V1",
                "ENABLED": "FALSE",
                "VALUE": 8
            }
        ],
        "HASHLIST": [...],
        "URI": "/menu_native/dynamic/tv_settings/audio/volume",
        "PARAMETERS": {...}
    }
    ```

Hope this helps!

[exiva/Vizio_SmartCast_API]: https://github.com/exiva/Vizio_SmartCast_API

**Comment by heathbar** [comment]
@sethlopezme thanks for the thorough write up!
