### ISSUE TITLE
Handshake Failure

### ISSUE THREAD

**Issue by grouma** [heathbar/vizio-smart-cast#9]
I'm getting the following error:

```
(node:1110) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Error: write EPROTO 3069649984:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 40
3069649984:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

(node:1110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is running on a raspberry pi zero w. I ran into this issue in the past and was able to resolve it but I have forgotten how. I have fiddled with updating the package but I have had no luck. This is on node version 8.1. Any idea what could be going wrong?

**Comment by heathbar** [comment]
There are reports of a firmware update that is causing SSL errors for people. That's my best guess until I get some time to research.

**Comment by grouma** [comment]
It's v4.0.23.2 with cast version 1.27.96538. The good news is that my one use, turning off the TV with my voice, is now solved by the device itself.

**Comment by heathbar** [comment]
@grouma are you able to try port 7345? I haven't received the new firmware yet, but others on 4.x have reported success on that port. 

https://github.com/exiva/Vizio_SmartCast_API/issues/15

**Comment by grouma** [comment]
Yup. I was able to manually connect on that port. I was also able to modify the port here https://github.com/heathbar/vizio-smart-cast/blob/master/index.js#L5 and connect as expected.

**Comment by exiva** [comment]
Not every set will get 4.0, and the older sets don't respond on 7345 to make that the default instead of 9000. So you'll have to switch somehow between 9000/7345. I'll have to do some digging in the Android apk to see how they handle this switch.
